# Generated by Django 3.2.16 on 2023-02-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_image',
            field=models.ImageField(blank=True, default=None, upload_to='media/update_pics/'),
        ),
    ]
