# Generated by Django 3.2.16 on 2023-02-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0003_updatecomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UpdateComments',
            new_name='UpdateComment',
        ),
    ]
