# Generated by Django 3.2.16 on 2023-02-10 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('site_updates', '0005_alter_updatecomment_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecomment',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
