# Generated by Django 3.2.16 on 2023-02-16 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0007_alter_updatecomment_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={},
        ),
    ]
