# Generated by Django 3.2.16 on 2023-02-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0008_alter_update_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='update',
            options={'ordering': ('-published_on',)},
        ),
    ]
