# Generated by Django 3.2.16 on 2023-02-17 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0009_alter_update_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecomment',
            name='comment_image',
            field=models.ImageField(blank=True, default=None, upload_to='media/comment_pics'),
        ),
    ]
