# Generated by Django 3.2.16 on 2023-02-20 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0010_alter_updatecomment_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='update',
            name='updated_on',
        ),
        migrations.AlterField(
            model_name='updatecomment',
            name='comment_image',
            field=models.ImageField(blank=True, default=None, upload_to='media/comment_pics/'),
        ),
    ]
