# Generated by Django 3.2.16 on 2023-02-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0011_auto_20230220_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecomment',
            name='action_image',
            field=models.ImageField(default=None, upload_to='media/comment_pics/'),
        ),
        migrations.AlterField(
            model_name='updatecomment',
            name='comment_image',
            field=models.ImageField(default=None, upload_to='media/comment_pics/'),
        ),
    ]
