# Generated by Django 3.2.16 on 2023-02-20 16:03

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0013_auto_20230220_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecomment',
            name='comment_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[600, None], upload_to='media/comment_pics/'),
        ),
    ]
