# Generated by Django 3.2.16 on 2023-02-20 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0014_alter_updatecomment_comment_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecomment',
            name='action_image',
        ),
    ]
