# Generated by Django 3.2.16 on 2023-02-20 16:49

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0015_remove_updatecomment_action_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatecomment',
            name='action_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[600, None], upload_to='media/comment_pics/'),
        ),
    ]
