# Generated by Django 3.2.16 on 2023-02-20 17:11

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0016_updatecomment_action_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='update_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[600, None], upload_to='media/update_pics/'),
        ),
    ]
