# Generated by Django 3.2.16 on 2023-02-20 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0017_alter_update_update_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updatecomment',
            name='comment_status',
        ),
    ]
