# Generated by Django 3.2.16 on 2023-03-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_updates', '0019_auto_20230220_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatecomment',
            name='comment_status',
            field=models.IntegerField(choices=[(0, 'Review Required'), (1, 'Review Complete')], default=0),
        ),
    ]
