# Generated by Django 3.2.16 on 2023-02-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, unique=True)),
                ('country_image', models.ImageField(blank=True, default=None, upload_to='media/country_pics/')),
                ('country_map', models.ImageField(blank=True, default=None, upload_to='media/country_maps/')),
                ('code', models.CharField(default=None, max_length=5, unique=True)),
                ('capital', models.CharField(default=None, max_length=100, unique=True)),
                ('region', models.CharField(default=None, max_length=100)),
                ('currency', models.CharField(default=None, max_length=100)),
                ('language', models.CharField(default=None, max_length=100)),
                ('about', models.CharField(default=None, max_length=500)),
                ('population', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
