# Generated by Django 3.2.16 on 2023-02-06 12:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='country_map',
            new_name='country_flag',
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='not_visited', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_map', to='diary.country')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_map', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
