# Generated by Django 3.2.16 on 2023-02-28 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_alter_diary_exp_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='exp_rating',
            field=models.CharField(choices=[('Not Rated', 'Not Rated'), ('Amazing', 'Amazing'), ('Good', 'Good'), ('Meh', 'Meh'), ('Bad', 'Bad'), ('Awful', 'Awful')], default='Not Rated', max_length=15),
        ),
    ]
