# Generated by Django 3.2.16 on 2023-03-01 12:21

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('diary', '0005_alter_diary_exp_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
