# Generated by Django 3.2.16 on 2023-03-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_alter_diary_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diary',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterField(
            model_name='diary',
            name='exp_rating',
            field=models.CharField(choices=[('Not Rated', 'Not Rated'), ('fa-face-grin-hearts', 'Amazing'), ('fa-face-smile', 'Good'), ('fa-face-meh', 'Meh'), ('fa-face-frown', 'Bad'), ('fa-face-angry', 'Awful')], default='Not Rated', max_length=25),
        ),
    ]
