# Generated by Django 3.2.16 on 2023-02-25 15:29

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/profiles/default-profile-img.jpeg', force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[300, None], upload_to='media/profiles/'),
        ),
    ]
