# Generated by Django 3.2.16 on 2023-02-27 14:13

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background_img',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/images/profile-bg-default.jpg', force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[1920, None], upload_to='media/profiles/background/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='objectives',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
