# Generated by Django 3.2.16 on 2023-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20230227_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='objectives',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
