# Generated by Django 3.2.16 on 2023-02-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_alter_profile_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='objectives',
            field=models.TextField(blank=True, null=True),
        ),
    ]
