# Generated by Django 3.2.16 on 2023-02-27 16:08

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_alter_profile_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_img',
            field=django_resized.forms.ResizedImageField(crop=None, default='media/profiles//background/profile-bg-default.jpg', force_format='JPEG', keep_meta=True, quality=-1, scale=None, size=[1920, None], upload_to='media/profiles/background/'),
        ),
    ]
