# Generated by Django 3.2.16 on 2023-03-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_alter_profile_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='background_img',
            field=models.CharField(choices=[('media/profiles/default-profile-img.jpeg', 'Paris'), ('media/profiles/rome-profile-bg.jpeg', 'Rome'), ('media/profiles/london-profile-bg.jpeg', 'London')], default='Paris', max_length=100),
        ),
    ]
